name: Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
    - name: 📥 Checkout the repository
      uses: actions/checkout@v3.3.0

    - name: 🏃 Hassfest validation
      uses: "home-assistant/actions/hassfest@master"

    - name: 📨 Discord notification
      if: ${{ github.event_name == 'schedule' && failure() }}
      run: |
        curl \
          -H "Content-Type: application/json" \
          -d '{"username": "GitHub action failure", "content": "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"}' \
          ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}

  validate-hacs:
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
    - name: 🏃 HACS validation
      uses: hacs/action@main
      with:
        category: integration

    - name: 📨 Discord notification
      if: ${{ github.event_name == 'schedule' && failure() }}
      run: |
        curl \
          -H "Content-Type: application/json" \
          -d '{"username": "GitHub action failure", "content": "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"}' \
          ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}

  validate-homeassistant:
    name: With Home Assistant
    strategy:
      matrix:
        channel: [stable, beta, dev, "2022.11.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: 📋 Copy sample configuration for Home Assistant
        run: |
          mkdir ./test_configuration
          bash scripts/install/frontend
          cp -r ./custom_components ./test_configuration
          echo "default_config:" >> ./test_configuration/configuration.yaml
          echo "hacs:" >> ./test_configuration/configuration.yaml
          echo "  token: CHANGE_ME" >> ./test_configuration/configuration.yaml

      - name: 🛠️ Setup Home Assistant
        id: homeassistant
        uses: ludeeus/setup-homeassistant@main
        with:
          tag: ${{ matrix.channel }}
          config-dir: test_configuration

      - name: 📨 Discord notification
        if: ${{ github.event_name == 'schedule' && failure() }}
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{"username": "GitHub action failure", "content": "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"}' \
            ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}